run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - goimports
    - gosec
    - govet
    - ineffassign
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
